import Head from 'next/head'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
    <h1 className="font-sans font-semibold text-5xl">Hello World!</h1>
    <p className="font-serif font-bold italic">Lorem ipsum dolor sit amet consectetur adipis necessitatibus deleniti delectus. Pariatur, veritatis ex?</p>

    </main>
    
    </div>
  )
}
